name: KBOT-CICD

on: push

env:
  TARGETARCH: amd64
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Run test
        run: make test

 